services:
  
  stream_helper_backend:
    container_name: stream_helper_backend
    build: ./
    networks:
      - stream_helper
    env_file:
      - ./.docker-compose-env
    volumes:
      - './prod-data/:/usr/app/data'
      - './video:/usr/app/public/video'
    depends_on:
      - stream_helper_redis
  
  stream_helper_lb:
    container_name: stream_helper_lb
    build: ./nginx-rtmp
    environment:
      - BACKEND_HOST=stream_helper_backend:5000
    networks:
      - stream_helper
    ports:
      - 1935:1935
      - 8080:8080
    depends_on:
      - stream_helper_backend

  stream_helper_redis:
    container_name: stream_helper_redis
    image: redis:7.4
    networks:
      - stream_helper

networks:
  stream_helper: