services:
  
  stream_helper_backend:
    container_name: stream_helper_backend
    build: ./
    networks:
      - stream_helper
    env_file:
      - ./.docker-compose-env
    volumes:
      - './prod-data/:/usr/app/data'
    ports:
      - 5000:5000
  
  stream_helper_lb:
    container_name: stream_helper_lb
    build: ./nginx-rtmp
    networks:
      - stream_helper
    ports:
      - "80:80"
    depends_on:
      - stream_helper_backend

networks:
  stream_helper: