name: Build Telemetry App

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - iracing-telemetry/**/*
    branches:
      - feature/*
      - fix/*
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Node Env
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Configure Environment
      run: rustup update
    
    - name: Build Package
      run: |
        cd iracing-telemetry
        npm install
        npm run tauri build
    

    
    # - uses: actions/upload-artifact@v4
    #   with:
    #     path: target/release/mylibrary.dll